### ISSUE TITLE
Won't accept paticular image URL

### ISSUE THREAD

**Issue by metal12345** [naschorr/auto-placer#1]
In Firefox
Works:
	let imageUrl = "https://i.imgur.com/AxKGmnJ.jpg";
Doesn't work:
	let imageUrl = "https://*****/test.jpg";

It doesn't log to console or run with the second example

**Comment by naschorr** [comment]
It looks like Firefox isn't dumping the cross origin errors into the console?  Chrome's giving me an `Access to Image at 'https://nakas.info/test.jpg' from origin 'http://pxls.space' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://pxls.space' is therefore not allowed access.` error, which would seem to indicate that it's an issue with the remote server. I'm not sure if there's much I can do on my end.

**Comment by metal12345** [comment]
That's it. Firefox does not dump CORS errors to console, I had tried with several versions of it
Previous bots worked becaue Greasemonkey can bypass CORS with unsafewindow

If anyone found this message helpful, please vandalize /r/touhou
