### ISSUE TITLE
It places the pixels on random coordinates

### ISSUE THREAD

**Issue by Grexal** [naschorr/auto-placer#5]
Basically title.
Even though I put the coordinates in the code (tried it both for bookmarklet and to the console), it always put the pixel in a random place. 

Am I doing something wrong?

**Comment by naschorr** [comment]
No, you're not doing anything wrong. It will randomly select a pixel from the image and also select the corresponding pixel from the board, making sure to check that two pixels are different. The random part is a bit of a relic from an earlier version and will be migrated over to a sequential version soonish.

**Comment by Grexal** [comment]
Oh, I thought something was wrong. Will wait for that sequential update!
Btw, will the output be the same size as the picture? Like if the picture is 100x100 pixels, will it be the same in the canvas?

**Comment by naschorr** [comment]
Yeah, it's an exact 1 to 1 mapping of pixels

**Comment by naschorr** [comment]
Just a heads up, I've pushed the changes to make it sequential. Everything should be working fine without any changes on your part, though.
