### ISSUE TITLE
UpdateTransform is not a function

### ISSUE THREAD

**Issue by SungMatt** [naschorr/auto-placer#7]
While using the bookmarklet, I'm getting an error 

`Uncaught TypeError: this.context.updateTransform is not a function
    at AutoPlacer.centerBoardOn (auto-placer.js?_=1498606425847:129)
    at Image.img.onload (auto-placer.js?_=1498606425847:86)`

How can I fix this?

**Comment by KrazyCone** [comment]
Me too idk
you on the hunt for an autoplacer too?

**Comment by naschorr** [comment]
Oh yikes, yeah I haven't touched this thing in ages and I'm not planning on fixing any bugs/compatibility issues. That said, feel free to fork the repo and fix things if you'd like.
